### ISSUE TITLE
Add translation for "Add photo" button

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#100]
On this page:
https://test-ceh-poms.pantheonsite.io/cy/enter-fit-count

one button translation has been missed. The button "Add photo" should be labelled "Ychwanegu ffotograff".

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin,

Don't worry about creating any further translation issues on these pages yet as am actively testing them, as am still working on an issues caused by having a mixture of English and Welsh pages.
Leave this issue open and I will fix the photo label.

I have fixed most of the serious issues which aren't translation apart from the species list not showing in Welsh Public FIT count anymore because of the page mode I am having to use.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Fixed, it may be wrong on the other two data entry forms, but leave that with me.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Sorry this won't be wrong on the other forms because they are English, but currently there is Welsh bleeding through I need to fix.
