### ISSUE TITLE
Allow larger file size for photo upload

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#111]
Users are finding it difficult to upload photos to the FIT Count form, as there seems to be a fairly low file size limit, smaller than on iRecord.

Can you let me know what the limit is?
Can we do anything to allow larger files to be uploaded and automatically reduced in size? That would be the best solution by far.
If we are unable to do that, can we adjust the error message workding so that it tells uses what the file size is?

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have set these options to match NPMS. Have you got an example of image that failed before, is it ok now?
The options that are set are:
@resizeWidth=1920
@resizeHeight=1080
@resizeQuality=75
@resize=3mb
@maxFileCount=10

**Comment by kitenetter** [comment]
@andrewvanbreda what does that mean in terms of the largest file that someone can upload?

**Comment by andrewvanbreda** [comment]
@kitenetter 
I think essentially this means it will try to downscale the image to be maximum of 1920 x 1080 (same as HD tv) and probably resize to 3 megabytes if needs to.
To be honest I am not 100% sure behaviour because it is automatic and am going by Indicia's code comments.
 Drupal and the server might have their own settings which are separate to this also.
What I did do is just try to upload a 12 megabyte image, and it did seem to accept that (although didn't save the sample, I think the problem usually occurs at the photo upload stage).
12 megabytes is huge for a compressed image by the way.

So really the best thing to do is get an image that didn't work before, and check it is working as you want now because it is hard for me to a precise explanation for the exact behaviour you'll see.

**Comment by kitenetter** [comment]
I'm still getting an "unable to upload" message for a file that is just under 5MB, do I need to clear the cache or something?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Maybe it is the type. Are you able to email the image or post it here so I can try the same image. I just tried 12 megabyte and was ok

**Comment by kitenetter** [comment]
@andrewvanbreda it seems to be working now, at least up to 6MB - it failed for a 17MB image but that is understandable!

Closing.
