### ISSUE TITLE
Spam registrations increasing?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#129]
We are getting a lot of spam registrations on the PoMS website, with active accounts in the last few weeks for multiple addresses linked to tacittender.site and fernreach.site. I will block these ones.

These accounts are getting activated, but don't appear to be adding anything to the website, so perhaps it isn't a problem. But if there is anything else we can do to avoid accounts from known spam sources to be blocked that would be good.

**Comment by BirenRathod** [comment]
@kitenetter This is a problem. I checked to day as well and there were three more registrations from last week Friday. I could stop but not worth investing time on Drupal 8 because I have already taken necessary action on Drupal 9. So would be good if we migrate site on Drupal 9 as soon as possible.

**Comment by kitenetter** [comment]
Okay, we'll focus on Drupal 9 for this. Closing.

**Comment by BirenRathod** [comment]
@kitenetter I recon sooner the better. probably we could plan something in next week.
