### ISSUE TITLE
Problems with user registration

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#135]
Not sure if @andrewvanbreda or @BirenRathod is best placed to help with this.

I've encountered two different problems with user registrations on the PoMS websitre this morning.

**1. Missing recorder name**
This applies to user https://ukpoms.org.uk/user/145 who registered 3 months ago.

They registered and their account was shown as active, but they were unable to add data. On their account page, there was no entry for first name or for surname. We have the surname set to be mandatory. I have now added the names and hopefully this is resolved, but the question is: 
- How did someone manage to register an apparently active account without completing this mandatory field?

**2. No agreement to terms**
This applies to user https://ukpoms.org.uk/user/303 who registered just over two weeks ago.

They registered and their account was shown as active, and I had given them the 1km square surveyor role, but they were unable to access the 1 km pan-trap form. When I try to masquerade as them, I get logged out of the system. The only anomaly I can see in their user account is that the box to "Accept Terms & Conditions of Use" is showing as unticked. Questions:
- Should I tick that box?
- How did they manage to register an active account without ticking that box?

**Comment by BirenRathod** [comment]
@kitenetter 1. I don't have any idea about it. It needs more investigation require as this is just one of user.

2. In Drupal 9, there is a "legal" module now in place instead of "terms of use". I have made mandatory of accepting terms and condition. The advantage of doing that is if there is a spam user registered already (which I deleted after I migrated but just in case there is) they can't able to compromise website and legal module keep the record of all users accepting terms and conditions.  Do we really want to make this not mandatory?

Martin, you can accept it as long as that user is aware or not having problem of accepting by you.

**Comment by kitenetter** [comment]
Thanks @BirenRathod 

I agree that acceptance of the terms must be mandatory. What I don't understand is how this user was able to register without accepting them.

I will try ticking the box and will see if that resolves the problem (and I will let the user know that I have done this on their behalf).

**Comment by BirenRathod** [comment]
@kitenetter This could be registered in old system and I just copied from there by accepted user.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter

My thoughts on this are:

1. 
Yes the Indicia Warehouse needs the surname to link to an account. So this would of failed until they filled it in the surname.
I have a feeling early on, that field had accidently been left as a non-mandaotry field

2. Is this because we have switched module, so the new module doesn't know about the tick on the old module.

**Comment by kitenetter** [comment]
For user https://ukpoms.org.uk/user/303 

If I go to edit their profile I am unable to tick the box to accept the terms - the box is not editable.

What do I need to do to enable this user account?

**Comment by kitenetter** [comment]
This is turning out to be a wider issue. I've just tried to masquerade as Nadine so that I can check everything is working for her to add the specimen bycatch data, and her account has the same problem with the terms tick box being unticked and non-editable.

This needs a solution urgently otherwise we will not be able to process the PoMS specimens.

**Comment by kitenetter** [comment]
Okay, this may not be quite such an urgent problem. Nadine has just tried to log on herself, and she got asked to confirm that she accepted the terms of use. She did so, and now the box is ticked.

So it appears that this does work as it should, but with the following constraints:
- The user has to log in and tick the box, I cannot do it for them (which makes sense)
- I cannot masquerade as a user who has not ticked the box (which is potentially problematic for those users who want us to sort things out for them)

Presumably this means that a large proportion of users who registered previously will have to tick the box to accept the terms again? I guess that is okay as long as they get clear information when they log on.

I will warn our regular volunteers that they are likely to need to confirm their agreement to the terms next time they log on.

**Comment by BirenRathod** [comment]
@kitenetter you can't checked that by yourself for user/303 unless that user has got same role as your one. Also in Nadine case, I just masqueraded , so should fine for you (if you are POMS support)

**Comment by BirenRathod** [comment]
@kitenetter Yes, all users (previously registered) should tick the box to accept terms. 
If you want to masquerade check first if that user has accepted terms and conditions.  
Yes, please warn if they have registered before.

**Comment by kitenetter** [comment]
This has not been raised as an issue recently. Closing.
