### ISSUE TITLE
Samples with missing location

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#136]
Four pan-trap samples have been entered without storing any value in the mandatory "1km square" attribute. Here is an example:
https://ukpoms.org.uk/add-1km-samples?sample_id=15177030

This may be a one-off glitch, and it is easy enough to edit and correct, but I wanted to raise it in case there is any underlying problem that we need to investigate.

If there is no obvious problem then I will edit the samples and we can close this issue.

**Comment by kitenetter** [comment]
Another example, from a different recorder - this is the only one out of 20 samples that is missing the location:
https://ukpoms.org.uk/add-1km-samples?sample_id=15357857

**Comment by kitenetter** [comment]
Also:
https://ukpoms.org.uk/add-1km-samples?sample_id=15501204

**Comment by kitenetter** [comment]
Also:
https://ukpoms.org.uk/add-1km-samples?sample_id=14727643

**Comment by kitenetter** [comment]
This example is one of six from this recorder where the location is missing (so that of their 20 samples, six are missing the link to the 1km square):
https://ukpoms.org.uk/add-1km-samples?sample_id=15510886

**Comment by andrewvanbreda** [comment]
@kitenetter 
I know at one point we did have a problem with the location field that I fixed (although I thought that was closer to start of project, and may not have been on this form)

So I cannot explain this behaviour at all. I cannot understand why usually it saves fine.
It is interesting that it is the pan trap form when the other one works in the same way.

I did just corrected 15510886 and it saved fine, so I have no explanation for what is happening.

I cannot think why a save would only sometimes occur.
I can confirm it isn't in the database though as I looked in the Warehouse UI (not a display issue).
The mandatory requirement is working I checked.
I checked one of the samples and the created/edit date is the same which means it wasn't edited in any official way after.

So I can only think of two possibilities

1. The data is being filled in, then the save does not happen correctly. I do not understand why that would be.

2. The data is being updated in some way after (maybe a scheduled tasks) which isn't updating the timestamp on the sample.

At the moment I am clueless

**Comment by andrewvanbreda** [comment]
@kitenetter 
Are you having any trouble with 1km FIT counts?, as the location autocomplete is ALMOST identical to the pan-trap form (see below).
(Aside from the helptext) - The only difference I can see is the pan trap form is not setup to set the grid reference field automatically and has to be typed by the user.

[location autocomplete]
@label=1km square
@helpText=Start typing the grid reference for the 1km grid square and select from the list - for example, type in "su" to find grid ref "SU6679".
@class=control-width-4
@validation=["required"]
@valueField=id
@captionField=name
@extraParams={"location_type_id":13870}
@formatFunction="function(item) { return item.name + ' (' + item.code + ')'; }"


[location autocomplete]
@label=1km square
@helpText=Start typing the 1km grid square and select from the list.
@class=control-width-4
@validation=["required"]
@valueField=id
@captionField=name
@extraParams={"location_type_id":13870}
@searchUpdatesSref=true
@formatFunction="function(item) { return item.name + ' (' + item.code + ')'; }"

**Comment by kitenetter** [comment]
@andrewvanbreda I have now filled in the missing names for all the pan-trap samples.

I can't find any 1 km FIT Count samples that have missing names, so this does seem to be an issue specific to the pan-trap data entry.

I hadn't realised that the 1 km FIT Count form was auto-filling the detailed grid ref box with the 1 km square grid ref. It shouldn't do that, sorry for not spotting this before! To stop that behaviour, can I just delete "@searchUpdatesSref=true" from the [location autocomplete] section?

**Comment by andrewvanbreda** [comment]
@kitenetter
I will do the change tomorrow, but yes you are right in theory.
I will just want to make sure their is not an unforeseen implication of the change.
I will also have a look at the pan-trap location problem again.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin,

I have made that change now.
Actually just thinking, for the future, can you let me know if you make any changes to the configuration that might  affect the code running.
This is simply because I may need to make the same change to EU PoMS and its associated FIT Count site as well as any of the TEST/DEV sites applicable to these projects.

In terms of this location problem.
I actually cannot see what might be the problem.

There are no javascript errors on the page.
It saves in my tests.
The location is mandatory when both adding, editing in my tests.
I see all the locations in the database are currently correct so I have nothing to go on their either.

The code and configuration between 1km FIT and Pan-Trap is almost identical, so I cannot see what is wrong at all.

Are you able to keep an eye out and let me know as soon as you know it has happens again?
 
I literally have nothing to go on at the minute.

Andy

**Comment by kitenetter** [comment]
We are unlikely to get further examples this year as data has now been entered for 2021. I'll close the issue but we may have to come back to it next year.

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK I have now raised this against the EU Pollinator project anyway as don't want that going live with similar issue, so perhaps there will be a fix before next year.

**Comment by kitenetter** [comment]
@andrewvanbreda the problem of missing locations for 1 km pan-trap samples has occurred again in 2022 - we have 32 samples (entered by several different people at different times) that are missing a location link. Here is one example:
https://ukpoms.org.uk/add-1km-samples?sample_id=20100518

I can manually add the locations for these samples so we don't lose the data, but it would be great if we could prevent this happening.

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK thanks for letting me know. I will look now as it might affect EU PoMS.

**Comment by kitenetter** [comment]
@andrewvanbreda I'm just starting to do the corrections, would you prefer me not to do that until after you've looked into it?

If needed the other sample IDs that I haven't yet corrected are:
18620541
18620894
18620936
18765471
19589994
19590015
19839237
19839245
19839288
19839342
19839584
19839625
19839627
19839637
19839796
20063794
20100530
20100548
20271211
20480655
20480733
20481335
20481368
20481464
20481605
20481669
20481680
20481700
20481736

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
I think you can do most of the corrections., maybe just leave 5 uncorrected for now.

I have checked the Warehouse UI, it seems 1km FIT Count doesn't have the issue, but EU PoMS Pan Traps IS having the same issue.

It is a very strange problem, as the location autocomplete is pretty much the same on 1km FIT Count and Pan Trap surveys.
It is also just a basic one, it doesn't have any custom code running on the control, just some standard configuration.

Thinking cap time.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter,

I have reproduced the problem.
 
The good news is that actually it isn't a saving algorithm failure (so you can have faith in that).

What is happening is there are a few location validations going on when the user clicks on the Save button, and one of these is broken on Pan Traps because there is a slight typo in the code.

One of these validators checks to make sure the pan trap grid reference is inside the grid square.
This works by chopping the spatial reference text off the front of the square name, then checking the pan trap main spatial reference fits inside that.
This IS working on all forms, and is usually sufficient for finding errors.

There is also another validator that makes sure a proper square has been selected from the square field, and it isn't just some invalid text, a proper selection has been made.

But there is a slight typo on the pan trap form that means this second validator is failing.
This typo is not present on the 1km form.

The first validator is usually sufficient, so that is why we are not seeing lots of errors given the number of samples.
This also explains why it passed testing.

However I have found a scenario where the square isn't saving.

This occurs if the user doesn't select the square properly from the squares drop-down list, and just types out a name, and then makes a typo mistake. 
In this case the square is not selected properly, but the usre will still have typed out the spatial reference at the start of the square name as text, so this fools the first validator.
And as the second validator is not working for pan traps, this problem is not caught on save.

As the square has not been selected by the user properly, nothing is saved (which is actually correct behaviour for the saving part).

The fix is simply to fix that broken validator, will let you know once done.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda for tracking that down. I will get back to correcting the missing ones later today. Please close this issue once you've completed the fix.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Fix is now live.
