### ISSUE TITLE
Consultant entomologist role has lost permissions

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#140]
The "consultant entomologist" role should provide access to the Indica page for entering species data for 1 km square samples, which is accessed via https://ukpoms.org.uk/select-samples-species-data

That page is not currently available for the consultant entomologist role. It was previously available so I don't know why this has changed.

If I look at the "edit role" options for the consultant entomologist role, under the "Indicia forms" sub-heading, it looks like I should tick the box for "species-data". Is that correct, and should any other Indicia forms be ticked for this role?

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK I will look. The support for this can be assigned to my EU PoMS timesheet as previously mentioned by David.
I have not changed the site at all recently so I do not know what has happened yet

**Comment by DavidRoy** [comment]
A wider issue with drupal sites that @BirenRathod is looking into

**Comment by andrewvanbreda** [comment]
@DavidRoy @BirenRathod @kitenetter 
I did just look at UK PoMS before seeing your message David.
It looks like most of the permissions selections have been wiped (the test site is the same).
Most pages are showing as administrator only (even things like My Results).
Masquerading as standard user is showing incorrect pages.
I will leave this in Biren's hands unless I hear otherwise.

**Comment by BirenRathod** [comment]
@kitenetter & @andrewvanbreda I have restored all permissions now.

**Comment by andrewvanbreda** [comment]
@kitenetter Please close this issue once you are happy with Biren's fix

**Comment by kitenetter** [comment]
Thanks everyone, that seems to be working again now. Closing.
