### ISSUE TITLE
Images "Insert" button not working

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#158]
This page (set up some years ago) has images nicely embedded and right-aligned:
https://ukpoms.org.uk/species-recording

I want to embed an image in a similar way on this page:
https://ukpoms.org.uk/poms-projects

However, if I use the image uploader at the foot of the edit screen for that page, when I click on "Insert" nothing happens. And if I try to add an image direct from the file manager interface I can't find a way of making it right-aligned within the text.

**Comment by andrewvanbreda** [comment]
Hi Martin,

There are errors on the page causing the Insert not to work, I suspect to do with the site setup or something, this is more Biren's area of understanding.

"was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)"
There are several of these errors.
These errors are Javascript errors I can see with Firefox's development tools.

In terms or the File Manager, I think those images can be inserted, but as you say, it is very difficult to use the user interface to get it to layout in the way we would want, it does funny things.
Even if we right-align, it does it in an odd way.

I suggest what we do is copy the raw html from the other page, and insert the different text and images into it.

I can help you with this I think, but I would need to know what images you are trying to use, and where you'd like them to go.

We can use this clone of live I made to get the page right before it goes live

https://avb-image-ceh-ukpoms.pantheonsite.io

Andy

**Comment by kitenetter** [comment]
Thanks Andy, I will check things with Biren when he's back. I have used the copying html approach before, but when I tried to do so yesterday it didn't produce the desired result (probably my error somewhere).

**Comment by andrewvanbreda** [comment]
@kitenetter 
OK, if you need something soon, go to the page in question on that test site and put the images you want onto it using the insert from file manager option and leave it unarranged. I will then try to arrange it for you if you give me an idea where the images should go.
I think there is inevitably going to have to be some raw HTML grappling required, I think even with that Insert button working I would be surprised if that suddenly allowed it to align perfectly using the interface.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda 

I just tried again using a different bit of html as the starting point and it has worked this time. I will check with Biren about the non-functioning "insert" button, but otherwise no further action is needed.

**Comment by kitenetter** [comment]
Insert button appears to be working now. Closing.
