### ISSUE TITLE
Setup privacy precision on data entry forms and test on reports

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#24]
@DavidRoy

Are you able to confirm if map blurring is required for user privacy reasons or species sensitivity reasons?
Thanks

**Comment by DavidRoy** [comment]
@CCarvell and @kitenetter to confirm

**Comment by kitenetter** [comment]
Map blurring is required for user privacy reasons, because:
- many FIT Counts take place in private gardens so we prefer to blur the precise location
- 1 km square surveys are on private land and we need to blur the precise pan-trap locations

Blurring to 1 km square level will suffice in both cases.

**Comment by andrewvanbreda** [comment]
Thanks @kitenetter

Thanks, that is all fine, I just needed to know as the way I implement the blurring varies depending on the reasons for it

**Comment by andrewvanbreda** [comment]
All data entry forms now protected to 1km for privacy. Just requires testing before closure

**Comment by andrewvanbreda** [comment]
All 3 types of data entry form setup up with same configuration. Have checked this configuration is also present on both languages versions. Have also checked this is working on Map Of FIT Counts, other reports will work in same way so closing now.
