### ISSUE TITLE
ElasticSearch - possible issues

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#42]
I still have some issues that is stopping me pushing forward with Elastic Search.

Some of this is related to the more limited capabilities for reporting. However I think there are two problems which I need your thoughts on

1. Currently Elastic Search doesn't currently return empty samples. Have you any thoughts on the acceptability of this. I am not sure a simple fix is available, but John said it might be a change needed for other projects.
If this is not resolvable quickly is this an unacceptable limitation.

2. Also I think Elastic Search doesn't return unreleased records. Martin I think you said Unreleased is necessary for verification reasons.
John said this could be overcome, but this would need us to work with him as it involves some data protection concerns.
I supposed the first question is do we still need the records to be unreleased.

**Comment by kitenetter** [comment]
**Empty samples**
Ideally we do need the reports to display samples that have zero occurrences, because we want to encourage people to submit results even if they don't see any insects, and if the resulting empty sample is not displayed people think the system isn't working.

I thought this had been resolved for the NPMS site, but not sure if that was using ES or not.

**Unreleased records**
There is no longer any need to have the records flagged as unreleased, because we can use the website agreements to prevent the PoMS data being passed to iRecord. (The only reason records were marked as unreleased on iRecord was to ensure they did not get displayed to verifiers or elsewhere on the site).

**Comment by DavidRoy** [comment]
@andrewvanbreda I thought this might be an issue.  I suggest you switch to PostGres queries for the reports for PoMs.  Longer term we need to extend the ElasticSearch Index to include samples with no occurrences

**Comment by andrewvanbreda** [comment]
@DavidRoy @kitenetter 
As far as unreleased is concerned, that is fine, I will remove the configuration that is doing that on the data entry forms.
Yes, will really push ahead now with doing those postgres queries, we can gradually replace with Elastic in future.
NPMS does allow zero abundance, but doesn't use Elastic Search. Elastic Search isn't very suitable for NPMS anyway as their is so much logic checking location attributes, persona attributes.....peoples right regarding squares and things.
