### ISSUE TITLE
Indicia page - map of FIT Counts

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#43]
This applies to:
https://test-ceh-poms.pantheonsite.io/fit-counts-map

Ideally, the columns to display are:
- Date
- Location
- Habitat
- Target Flower
- Photo of target flower
- Total number of insects

If possible, it would be good to show both the public and the 1 km FIT Counts on this single map, but the public counts are the priority.

If possible, it would be good to have filter boxes at the top of the columns (but this is not essential).

Normally we only show counts for the current year, and this has been specified via a parameter in the report settings. Is that the best thing to do for 2021 and beyond, or is it possible to have a dropdown filter box that allows users to select a year, and that goes to the current year by default?

**Comment by kitenetter** [comment]
This page currently has the standard iRecord tools for "Create a filter" but few of these are relevant to PoMS, and the column-head filter boxes will be sufficient. Otherwise we will have to make a lot of change to the "Create a filter" tools.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes that is fine, I have been too distracted with various things to work on this yet. Will be doing that over the weekend. Thanks for the note though

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,

I have done an initial version of this report that has now been commits into indicia-reports, PoMS.
Two reports are

fit_counts.xml
fit_counts_mapping.xml

Can you pull these onto Live Warehouse please

Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda 
I have pulled those reports on to live warehouse now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, will take a look this morning

**Comment by andrewvanbreda** [comment]
@kitenetter @DavidRoy
Have put this on test site, also the My Counts page should be working.
I realise there are some things that need address still such as
- Default the year
- Setting the colours on the map depending on the counts
- Other enhancements
- General checking for any bugs

Could you let me know what colours you would like to use for the map in relation to counts.

AVB Edit: Note I am aware the Location/Target Flower columns not working at moment. I will fix this

**Comment by andrewvanbreda** [comment]
@kitenetter 
Hi Martin,
I fixed the year. Let me know about the colours. I also fixed the Target Flower which was a bug (although this fix isn't on site yet).
However the Location not displaying is actually correct. This is has been automatically protected due to the Privacy Precision setting.
Let me know your thoughts on this? The name of the place won't get displayed because of that, an alternative might be to try and display the blurred spatial reference.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Let me know about the colours for the map, think the other bits are resolved now

**Comment by kitenetter** [comment]
Before we get to colours, I need to catch up what we are actually going to display on the map. My recollection is that we were aiming to show counts as 1 km squares rather than precise locations, is that going to be possible? If it is, then it would be nice to have a colour ramp that indicates how many counts are in a 1 km square, but I don't have a strong opinion as to what that colour ramp should be.

It would be nice to be able to click on a square on the and have the grid filter down to the records in that square, and vice-versa to be able to click on a record in the grid and have the map zoom in to the correct location.

Can we set the default grid view give the most recent record at the top of the grid?

The "Survey" dropdown filter is not currently displaying an option for the app records.

**Comment by andrewvanbreda** [comment]
@kitenetter
Yes can fix the last two, the colour ramps would be possible.

I think I raised somewhere inconsistencies in the spec in this area which talks about squares, but also talked about samples and clicking on individual counts:
I see now that you are expecting it to transition between types as you click on map. This was not taken into account by me when estimating.
I did do something similar for a project about 8 years ago, so I will see what that code did.

The spec says
"A1.1 Map display of public FIT Count data (user not logged in) 
This should allow any website visitor to see the results as they come in, ideally with some colour-coding to show number of counts in a square. Possible functionality:
1.	Click on square to see counts for that square listed in grid under map
2.	Click on any one count to see summary info for entered attributes: target flower, no. of flowers, quadrat context (isolated or in flower bed etc.) habitat, total number of insects, number of insects in each group
3.	Show a simple comparison between number of insects counted and an average (most likely the average total insects for all counts in the same month in the same country)

Note that these reports need to output samples, not just occurrences, as some samples are zero counts with no occurrences.

Not yet clear: whether we can calculate averages from the Indicia database, or whether we need to provide suitable data as a lookup table."

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have looked into the viability of solutions to what you want.
I think what might be possible, which should be easy IF it works is as follows (I think the alternatives to this are far too difficult to implement for this project from what I can work out. I have it in a project about 8 years ago, but the code is too complex to even lift out for this project).
I propose the following:
- Grid shows samples, clicking does zoom the map to the sample
- Indicia maps can support two reports, one for when the map is zoomed in (samples), one when zoomed out (squares).
The question is when you zoom in at what point does it switch, but perhaps that is changeable.

I think this is the solution that could be implementable for live, I will have to see tomorrow. Actually IF it works, it should be easy.

It does mean the switch occurs as you zoom in or if you click on grid, rather than on square click.
Although this might actually have an advantage as it might allow for us to display information if the user clicks on a square, which probably wouldn't have been possible if that caused the samples to be shown.
I will have to experiment tomorrow.

An extra thought I just had is that instead of doing anything fancy like my previous project, we might actually be able to simply allow clicking on a square to zoom into the required level of the map for the switch to samples to automatically occur. I think this might work, it sounds like an elegant solution.

**Comment by andrewvanbreda** [comment]
Note the above notes are now out of date and not necessary. The confusion was caused by the app not setting privacy precision on the samples, if this is set, then these samples will be shown at 1km level anyway.
The existing samples report will suffice in this area.

**Comment by kitenetter** [comment]
The FIT Count map is currently working well. We could consider further enhancements (e.g. to enable a link between the dots on the map and the count data in the table) but will open a new issue if that becomes a priority.
