### ISSUE TITLE
Clarify best structure for existing records grids

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/PoMS#48]
There are currently some issues with the number of different grids that are required for existing data (and then doubling this as there are English and Welsh versions)

Thoughts on a possible simplification of this?

Currently I added the following

"Select pan-trap samples....."  for Bycatch added to "Add your records" menu
"Select pan-trap samples....."  for insect species added to "Add your records" menu
"My data" added to "Explore records" menu (allows viewing of any type of record they my have entered on site + app)
"FIT counts map" added to "Explore records" menu
"List or edit samples" added to Administration menu (allows viewing/editing of any type of record  on the site + app)

One question, am a bit confused if you wanted to the FIT Counts Map to display just the Public FIT Counts entries or what did you want it to apply to?

**Comment by kitenetter** [comment]
**Menu structures**

The terminology needs some care, and here is what I've ended up doing:
- menu "Taking part" tells you what surveys PoMS runs, and how to do them
- menu "Add your results" will be where you go to add the results of your standard FIT Count, and if you are registered as a 1 km square volunteer you will also be able to add your 1 km square FIT Count and 1 km square pan-trap results
- menu "View results" allows you to see your own results (for all PoMS surveys that you have taken part in) and also provides the link to the FIT Counts map (which is viewable by anyone)

I have used the word "results" because:
- "data" feels a but technical and offputting given our target audiences for the FIT Counts
- "records" feels inappropriate for PoMS, which for the most part is not producing species records, but is producing a wider range of pollinator-related data

@CCarvell I am happy with the above approach but let me know if you have any concerns

**FIT Counts map**
This should ideally display samples for all FIT Counts from all sources, i.e. public counts added via the app + public counts added via the website + 1 km counts added via the website. There should probably be an edit button for samples that you have added yourself, although this is not essential because you can use "My results" to edit your own samples.

The current grid for the FIT Counts map seems fine to me, although as yet not all the attributes are being populated (target flower is currently empty, and we have agreed to display the 1km square rather than the location name).

**"My results" grid**
I am happy with the idea of using a single grid to display the samples for all surveys that the user participates in. However, the survey attributes for the FIT Counts are quite different to the survey attributes for the pan-trap surveys.

A grid that should work for both would contain:
- sample_id
- location name if possible (although the locations are sensitive, can we allow the name to be shown for people editing their own records?)
- 1 km grid ref
- detailed grid ref (this could be dropped if the grid is getting too full)
- date
- start time (FIT Counts only)
- pan-trap number (pan-traps only)

The other attribute that is not necessary in the "My results" grid, but is needed for overall admin and for the "Select samples to add ..." page is:
- recorder name 

If it is simplest to add recorder name to the "My results" grid and then use the same grid in all places I think that will work.

However, I'm not clear how these "one grid for all reports" works alongside the "Select samples to add ..." functions, where the edit buttons need to take you to different places depending on whether you are adding bycatch or adding species.

Happy to discuss this again @andrewvanbreda since I am not certain if have have answered the questions you had.

**Comment by CCarvell** [comment]
@kitenetter I am happy with the menu structures you propoe above, agree we should use "results" not data

Probably not relevant, but in the "My results display, will the FIT Count samples that are shown definitely contain the name of the target flower chosen for each count? 
Having the recorder name appear in the My results grid makes sense for people who many want to share and combine their counts with others in a group (note this 'sharing' function is not something we are going to support on the website, it's for them to do separately if they wish).

**Comment by andrewvanbreda** [comment]
Hi @CCarvell @kitenetter 

Using the term "results" is fine, I used "data" simply as a term that was more general than "counts" and was never intended to be the final term.

Yes the FIT Count Map showing all survey's will be fine I will change that. Very easy change.

In regards to the attributes
- The Target Flower is fixed in code, but that code hasn't been moved onto BRC's server yet.

- The Location field has been noted but haven't had time to action yet.

In terms of "recorder name", that can be aded to the grids

In terms of the "Select samples to add ...", these will be separate pages controlled by roles as before.

I think it is better to think of this as a reduced number of grids, not one grid
(note the list of 5 grids pages I have referred to in the first comment of this thread).

Essentially the current plan would be to have:
My Results (own records from all surveys)
Fit Count Map (Data results for all users to see)
List or edit samples (results for admins, editing available for any records)
"Select pan-trap samples to add insect BYCATCH data for 2020" (role controlled)
"Select pan-trap samples to add insect SPECIES data for 2020" (role controlled)

I have some work to do on the Plant Portal project at the moment, but I will try to action these points as soon as I can.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter @CCarvell,

I have been trying to deal with this this morning. 
I have made quite a lot of changes to reports running on my own machine (so you won't see the changes yet)
However I think I should check some things before I commit.

Ultimately I will now use a different report for "my results" and "all results".
This will allow me to specify the location and detail spatial reference on the "my results" grid and map.

1. It wasn't clear to me whether you want recorder names on "my results".

2. The "A grid that should work for both would contain:" list above seems to be missing the target flower columns, don't you want those?

3. Do you want a column indicating which survey (or app) the row came from?

4. Another option is if the attributes are too different, we could have more than one grid on the same page.
Let me know if you think that is a good idea?

**Comment by kitenetter** [comment]
Thanks Andy. I'm not sure what you mean by "all results", is that the FIT Count map?

1. Ideally it would be good to have recorder name in the "My results" grid, because some users will add results from more than one recorder. However, if that make the grid look too congested it could be left out.
2. In the "My results" grid the target flower is less important I think. It is needed for the FIT Counts map, but a user trying to find one of their own counts would be more likely to search by date or location. I have no objection to target flower being included, but again I'm worried that it will make the grid too congested.
3. Yes, I think we do need a way of specifying which survey for the "My records" grid. This could be a column in the grid, or I suppose it could be a filter box similar to the year filter that you've provided for the FIT Counts map. I don't think we need to have the survey included in the grid for the FIT Counts map (again so as to avoid making the grid congested).
4. Can't work out whether having two grids will make things simpler for the user, or more complex. This is only an issue for those users who take part in the pan-trap surveys, whilch is only about 60 users and will never be more than about 80. The priority is to have a grid that works well for people who have submitted FIT Counts, while also allowing the small number of pan-trap survey contributors to get back to their own records if they need to edit them.

**Comment by andrewvanbreda** [comment]
Hi @kitenetter 
Thanks for responses.
I will implement these suggestions on my machine and let you know if I have further questions.
Sorry by "All Results" I meant the Fit Count Map (although this same report may end up driving the administrator equivalent page hence the general name). I said All Results because that is the filename I have given the report, obviously it slipped my mind you didn't know this.
In regards to point 4, I think one grid will probably be the way to go given what you are saying.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
I have written some new reports, are you about to pull these onto the Live Warehouse please. Obviously this is risk free at the moment as the project isn't live.
Thanks

indicia-reports/projects/PoMS/all_poms_results.xml
indicia-reports/projects/PoMS/all_poms_results_mapping.xml
indicia-reports/projects/PoMS/my_poms_results.xml
indicia-reports/projects/PoMS/my_poms_results_mapping.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda 

Those reports have gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren. 
Looks those changes are there fine as it says it can't find the old report which is what I am expecting. 
Will configure over the weekend.
Cheers

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Whenever you get chance I have made some alterations to reports for bug fixes and suggestions made by Martin/Claire in other threads, could you pull these reports onto live whenever you get chance (I have renamed them again also). Cheers

projects/PoMS/blurred_poms_results.xml
projects/PoMS/blurred_poms_results_mapping.xml
projects/PoMS/poms_results_in_detail.xml
projects/PoMS/poms_results_in_detail_mapping.xml
projects/PoMS/result_counts.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled those reports on live warehouse now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren,
Will configure those this morning

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
I have made some further important changes, can you pull the following again, cheers.
projects/PoMS/blurred_poms_results.xml
projects/PoMS/poms_results_in_detail.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda, done.

**Comment by andrewvanbreda** [comment]
@BirenRathod Thanks Biren

**Comment by andrewvanbreda** [comment]
Going to close this issue now. Individual problem cans be raised separately.
