### ISSUE TITLE
Agree an overall menu design

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#53]
When logged out, the menu item appears with no sub-menu items and does nothing.

@kitenetter I'm not sure how you want this behave

**Comment by kitenetter** [comment]
I always find Drupal menu behaviour confusing.

We do want logged-out users to be able to add FIT Counts and see the FIT Counts map.

There is a similar issue with "View results" and "Reports and research", whereby the top-level menu item does not do anything.

@andrewvanbreda is there a 'best practice' way of dealing with this? Do I need to create new pages that will appear if people click on the top-level menu items, and then list the submenu links on those new pages?

Or is there something more automated that we can do?

On iRecord there are top level menu items that only work if you do a double-click, and last time we tried to find a better approach to this we seemed to get stuck with drupal limitations.

**Comment by BirenRathod** [comment]
@kitenetter You don't need to create new pages. There is very good way to control menu items for each role & anonymous user.

If you can list me the menu items which should be available to anonymous user, I can add permission for it. so they will be available for non login user. 

Also, here are two way to manage menu item, one which has got page link with it one without. So it all depends which page need or not needed. Do not use iRecord menu as an example as it has created in very early days using part Drupal & Part John's code.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,

Should I enable the Menu Item Visibility module, then I can deal with this situation for you. I am doing the rest of the page permissions, so prob less confusing if I do it

**Comment by BirenRathod** [comment]
@andrewvanbreda yes, please. As I mentioned before feel free to enable module as you required.

**Comment by kitenetter** [comment]
Thanks @andrewvanbreda - let me know if there is anything I need to do for this

**Comment by andrewvanbreda** [comment]
@DavidRoy @kitenetter 
I have corrected these particular problems now with unregistered users in both English and Welsh versions.
Please close this issue if you are happy the original issue is resolved.

**Comment by kitenetter** [comment]
This may already be in hand, but at the moment we have three top-level menu items that do not provide a page when clicked on:
- Add your results
- View results
- Reports and research

**Comment by andrewvanbreda** [comment]
Will fix, they should be inactive and non-clickable

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
I see the butterfly monitoring site does this also, do you know how the theme can be prevented from doing this?

**Comment by BirenRathod** [comment]
@andrewvanbreda Sorry I don't understand this. what you want me to do in this issue?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
It is what Martin mentioned in this comment

"This may already be in hand, but at the moment we have three top-level menu items that do not provide a page when clicked on:

Add your results
View results
Reports and research"

I think what martin is saying is that the menu headings are still clickable, but don't do anything. It is like a link that goes nowhere, where we don't want it to react to the click other than show the drop-down.
Try it and I think you will see what I mean.

U may want to confirm with Martin if you are unsure because I am only interpreting what I thinks he meant.

**Comment by BirenRathod** [comment]
@andrewvanbreda I checked the links.  It shows hover on that link and because it hasn't got any page link with it, it should not go anywhere and stays there.

**Comment by andrewvanbreda** [comment]
@kitenetter @BirenRathod 
Thanks Biren.

Martin: As you raised the issue originally you will need to be the one to say whether or not you are ok with this.

**Comment by kitenetter** [comment]
I still find the menu behaviour confusing, but I'm not sure if others react the same way as me.

- At the moment, if I click on "Home" it takes me straight to the home page, which is what I expect. If I hover over the "Home" menu item I can see some other sub-menu choices.
- If I click on "Taking part" it takes me straight to a taking part page, which is what I expect. If I hover over the "Taking part" menu item I can see some other sub-menu choices.
- If I click on "Add your results", the page appears to re-load, but in fact stays on whichever page I was already on. That is the bit that I find unhelpful.
- Similarly, if I click on "View results" or "Reports and research", the page re-loads but doesn't change.

I would like *something* to happen when I click on each of the top-level menu items! Using "Taking part" as an example, the options seem to be:
1. Make the menu behave so that if I click on "Taking part" it automatically goes to the first sub-menu item under that heading.
2. Add an additional page that would appear when "Taking part" is clicked - that page could simply be a list of the sub-menu items.

Neither of those is ideal. Option 1 means that there are two menu items that both go to the same place. Option 2 is likely to cause problems for users who aren't logged in (because some of the sub-menu items are intended to be hidden for non-logged-in users).

Not sure what the best solution is, but I will add pages as per option 2 unless anyone has a better idea.

**Comment by BirenRathod** [comment]
@kitenetter 
There are two options available "Mouse hover" & "Mouse click". So "Mouse hover" suppose to display drop down menu if there is. "Mouse click" suppose to take the link to the page if page is exist. because there is no page exist, it is not taking anyway but it should show "Hand" gesture as it has got dropdown menu with it.

You have confused with "Mouse click", as you expect mouse click should display the drop down link as this website warehouse1.indicia.org.uk does, which is not suppose to be like that. If you look at any website, it does what I done on all menus of Pantheon website. take a look this for e.g. -> https://www.wildcoms.org.uk/ 

So my recommend is create the page for each of those links and add submenu links in those pages too.

**Comment by andrewvanbreda** [comment]
@BirenRathod @kitenetter 
Hi,

I am personally not a great fan of sub-menus that have an active heading (although I realise my opinion isn't the decisive factor here). I have seen projects in the past have problems with this where people then don't notice there is a sub-menu (admittedly the PoMS admittedly displays the sub-menu instantly, so shouldn't be an issue).

Personally I think 
1. Home should just be a link. No sub-menus. Move those Home items into separate menu with different name.
2. I think "Taking Part" should be changed to have an extra new sub-menu item which goes to the "Taking part in PoMS" page, the menu heading can then be made inactive.
3. All the View Results, Administration, "Reports and research" headings should not be clickable.

Biren, is my understanding correct that this would be possible by using Mouse Hover?
How is that mode changed so we can at least experiment?
Cheers

**Comment by BirenRathod** [comment]
@andrewvanbreda How to layout menu, that is @kitenetter can decide. From my perspective, I should provide the features the way menu should behave in general.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Yes I realise Martin will decide, but that is my thought on what might work well.

**Comment by andrewvanbreda** [comment]
@kitenetter 
Assigning to you to comment on proposals.

I should also point one further thing out, my suggestions should also avoid the problem where if there is a sub-menu, the user might not even notice the the main heading is clickable too.

**Comment by kitenetter** [comment]
Okay, I'm going to go with @andrewvanbreda suggestion that where sub-menus exist the top level menu item should not be clickable (mainly because to add top-level pages would have knock-on requirements for additional translations). I will re-organise the menu structure slightly to ensure this is consistent.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Is this feasible?

**Comment by BirenRathod** [comment]
@andrewvanbreda Basically not be clickable means no leading page link. and that simply means just disable that link. You just need to disable the top menu link, so only hover is available to display a drop down menu.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod,
This is the problem I have though, the top-level links were always disabled & set to "<nolink>",  but are still active anyway. So this is the issue I don't understand how to fix.

**Comment by BirenRathod** [comment]
@andrewvanbreda Instead of storing with blank string like this "", use `<nolink>` which should disable it.

**Comment by BirenRathod** [comment]
> When logged out, the menu item appears with no sub-menu items and does nothing.
> 
> @kitenetter I'm not sure how you want this behave

    @kitenetter those should not be visible. Do you want me to do that or are you ok to do that?

**Comment by kitenetter** [comment]
@BirenRathod I can no longer see any problem with menus when logged out. I need to do a final review of which menu headings we use but I don't think there are any other remaining issues here.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
There was a typo in my message, they are currently set to nolink and it doesn't work.
You actually aren't allowed a blank string

Actually just realised whey I had a typo in my previous message, when I type that GitHub is removing it.

The page still reloads on clicking heading

**Comment by kitenetter** [comment]
I think the only issue left here is that the `<nolink>` top-level menu items are still forcing a page refresh. Would be good to prevent that if we can.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Biren at you able to comment on a fix for this?

**Comment by BirenRathod** [comment]
@kitenetter & @andrewvanbreda Don't worry too much at present about menu bit, it will get fix with new theme.

**Comment by kitenetter** [comment]
Thanks @BirenRathod and the new design demo has just been circulated, in which the menus work in a slightly different way and this problem is no longer an issue, as you said. Closing.
