### ISSUE TITLE
Website pages sent to Transifex

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/PoMS#55]
This is an issue to keep track of pages signed off and sent for translation.  
@CCarvell @kitenetter. Please confirm order of priority for translation and which, if any, require sign off for translation

sent for translation
- [x] home page. https://test-ceh-poms.pantheonsite.io/
- [x] contact. https://test-ceh-poms.pantheonsite.io/contact
- [x] FAQs. https://test-ceh-poms.pantheonsite.io/faqs
- [x] taking part. https://test-ceh-poms.pantheonsite.io/taking-part
- [x] taking part. FIT counts. https://test-ceh-poms.pantheonsite.io/fit-counts
- [x] taking part. One km survey square. https://test-ceh-poms.pantheonsite.io/one-km-square-survey
- [x] About. https://test-ceh-poms.pantheonsite.io/about
- [ ] View results. Map of FIT Counts. https://test-ceh-poms.pantheonsite.io/fit-counts-map
- [ ] View results. My results. https://test-ceh-poms.pantheonsite.io/my-results
- [x] Species recording. https://test-ceh-poms.pantheonsite.io/species-recording
- [ ] Add your results. Enter-fit-count. https://test-ceh-poms.pantheonsite.io/enter-fit-count
- [ ] Add your results. 1km FIT count. https://test-ceh-poms.pantheonsite.io/1km-fit-count
- [x] Reports and research. PoMS project reports. https://test-ceh-poms.pantheonsite.io/reports
- [x] Reports and research. PoMS research. https://test-ceh-poms.pantheonsite.io/research
- [x] Reports and research. Data from PoMS.  https://test-ceh-poms.pantheonsite.io/data
- [ ] Add your results. 1km square survey - pan-trap results. https://test-ceh-poms.pantheonsite.io/add-1km-samples
- [ ] Add your results. Select pan-trap samples to add insect bycatch data for 2020. https://test-ceh-poms.pantheonsite.io/node/6
- [ ] Add your results. Select pan-trap samples to add insect species data for 2020. https://test-ceh-poms.pantheonsite.io/node/7

**Comment by CCarvell** [comment]
thanks @DavidRoy 
This is the main remaining page which I am expecting to edit and sign off this week: 
Reports and research. PoMS research. https://test-ceh-poms.pantheonsite.io/research

All other core pages (that don't require authorised login) are signed off BUT I have not reviewed any of the results or report pages yet. Will aim to access in next 2 days. But @kitenetter should be the main reviewer of the results and reports pages.

**Comment by CCarvell** [comment]
@kitenetter or @andrewvanbreda minor edits for this page please, then I think it is ready to translate from my perspective.
Add your results. Enter-fit-count https://test-ceh-poms.pantheonsite.io/enter-fit-count

**First yellow text box, edit to say UK PoMS and one typo:**
"This FIT Count is being submitted to the UK PoMS website. If you have **a** website account, please log in so that this Count appears in your "My records" list. If you are not already registered with UK PoMS we recommend to register so that you can view your previous Counts and use all the site’s facilities."

_How did you hear about the FIT Count?_ - this is still showing but I thought we had agreed to remove it from the app and from each version of the Count data entry form. The preference was to capture this information using a separate questionnaire to users.

_Taking part in the FIT Count was:
Carrying out the count was:_
Likewise, I thought we had agreed to remove these quesitons from every count and capture the feedback separately - they are not included on the app.

**Comment by CCarvell** [comment]
View results. Map of FIT Counts. https://test-ceh-poms.pantheonsite.io/fit-counts-map

This page seems fine to me for translation.
I have a query about the zoom resolution on the map - to confirm that 1 km squares will not be identifiable to 1 km level by non-registered users (we do not share locations publically beyond the 10km scale).

**Comment by andrewvanbreda** [comment]
@CCarvell 
There are two test samples on the system, they should be 1km protected. It looks to me like they are but feel free to have a look yourself. If you don't think that is the case, let me know with explanation of your thinking so I can look into it.

**Comment by andrewvanbreda** [comment]
Hi @CCarvell 
I fixed the typo and added UK PoMS. However I have not removed those questions yet. I can remove them but I wanted to confirm you definitely don't ant any of this information captured for unregistered users, and registered users only have the question about hearing about the survey on their account page.
Please confirm this is what you want.

**Comment by kitenetter** [comment]
@CCarvell I'm a bit alarmed about the 10km resolution suggestion, I wasn't aware that this was a requirement.

On iRecord at the moment, non-logged in users can see public FIT Counts at full capture resolution, and always have been able to. So the 1km blur provides a greater degree of blurring than we have previously had.

For the FIT Counts originating from the 1 km squares we have not made these publicly viewable in the past, and as things stand they will be publicly viewable, at 1km square level, on the new site. Do you have concerns about this?

If you do, I think we will have to omit the 1 km FIT Counts from the map altogether, as I feel that having some couts diaplyed as 1km and some as 10km would be unnecessarily confusing.

This also has implications for the maps that I hope we will be able to display that show the locations of all the 1 km square surveys, and whether they are adopted or not. As things stand we have not specified a 10km blurring for this.

My understanding was that when we publish PoMS data that will also be at 1km square level, so the 1km squares are going to be in the public domain one way or another.

**Comment by andrewvanbreda** [comment]
@CCarvell @kitenetter 
Hi, just to clarify my understanding.
All the 3 data entry forms are currently blurred to 1km for both registered and unregistered. If you see anything other than this, let me know.
Nothing relating to 10km has been implemented at the moment.

Note that I am making the assumption the app handles applying the 1km privacy precision itself

**Comment by CCarvell** [comment]
@kitenetter you are completely right about the 1km square resolution, my apologies to you and @andrewvanbreda  for getting confused and rushing to make that comment. I was thinking from the perspective of the maps we normally produce for our reports and to flag 1 km squares available to adopt, which are necessarily at large (10km) scale due to the A4 print size. Until now, people have had to email us to request further info about specific locaitons of the 1 km squares in their area.

Of course, as soon as we start making the survey data available by 1 km square, that location information will be in the public domain (although it's a bit less 'public' when it has to be reached via EIDC than via the PoMS website). We did make this clear to landowners in our initial access permission letters.

**For the 1 km square maps (showing adopted vs non adopted squares) and 1 km FIT Counts map:**
To be absolutely sure that this approach is not problematic for either of the two other schemes with which our squares are co-located, I will contact Angus and Bron (ref ERAMMP in Wales) and Oli and Rachel/ Plantlife (ref NPMS in Scotland and England) to explain how the new PoMS website plans to display squares at 1 km resolution. 

So, the upshot is that I think you can continue as planned and ignore my comment about the 10km blurring, but hopefully we will get the OK on this from the other schemes.

**Comment by andrewvanbreda** [comment]
@CCarvell 
No problem Claire, actually I didn't even notice it at first, I will leave the system as is.

**Comment by andrewvanbreda** [comment]
@CCarvell 
Oh and can you let me know about what I have written here as I think it has got lost amongst the talk about square resolution.
Thanks

"I fixed the typo and added UK PoMS. However I have not removed those questions yet. I can remove them but I wanted to confirm you definitely don't want any of this information captured for unregistered users, and registered users only have the question about hearing about the survey on their account page.
Please confirm this is what you want."

Thanks

**Comment by CCarvell** [comment]
@kitenetter could you please confirm your understanding of what we decided about the question
How did you hear about the FIT Count? - and the two feedback questions at the end of the FIT Count form? 
None of these are present on the app Beta version (either at the Register stage or within each count survey), so I was assuming we would also remove them from the new website forms. Did we decide to retain the How did you hear about the FIT Count? drop down just for users as they Register on the website, as Andy is suggesting? Thanks

**Comment by andrewvanbreda** [comment]
@kitenetter @CCarvell 
Just to note, it isn't my suggestion as such, it is simply my understanding of what you wanted, but then I noticed the other two questions would be lost. Entirely up to you how to proceed, I just wanted to let you know what I noticed.

**Comment by CCarvell** [comment]
@DavidRoy to note that Welsh Gov have said it will not be necessary to provide Welsh translation of the 1 km square survey online data entry forms.
Add your results. 1km square survey - pan-trap results. https://test-ceh-poms.pantheonsite.io/add-1km-samples
 Add your results. Select pan-trap samples to add insect bycatch data for 2020. https://test-ceh-poms.pantheonsite.io/node/6
 Add your results. Select pan-trap samples to add insect species data for 2020. https://test-ceh-poms.pantheonsite.io/node/7

**Comment by andrewvanbreda** [comment]
Does this mean the term lists shouldn't be translated? 
I just started but only done a few terms so far as a test. I assume we don't want Welsh terms if rest of page is in Welsh?

Note I have noticed a problem where actually both the english and welsh terms are showing in the drop-downs at the moment, I have seen this happen on another project, so I will have a look what I did to fix that situation.

**Comment by kitenetter** [comment]
@andrewvanbreda @CCarvell 

My understanding is that want to keep the FIT Count data entry form as focused as possible on the counts. So the form will **_not_** include:
- Your identification experience
- How did you hear about ...
- Taking part in the FIT Count was ...
- Carrying out the count was ...
- I am happy for you to contact me in connection with PoMS

It would be good if the website registration process can match the app process as closely as possible, which means adding these questions to the registration process:
- Your identification experience (using the same termlist as currently on the form)
- Are you happy to be contacted (yes/no, with default set to no)

We are no longer using "How did you hear about" within the app, nor within the website.

For those people who both register and opt in to being contacted we will be able to send questionnaires to gather information on how they heard of us and how much they enjoyed taking part etc.

For those people who register but do not opt in to being contacted we have no options.

For those people who add counts without registering we also have no direct options, but as and when we produce questionnaires we can add links to the website so that non-registered users could complete the questionnaire if they wish to. Optionally we could also set up an opt-in to email communications that non-registered users could sign up to. But that is additional complexity that we can revisit later on.

**Comment by CCarvell** [comment]
Thanks @kitenetter that is all perfect. 
If you/ Andy can make those adjustments to the form and registration, then I think they should be ready for translation.

**Comment by andrewvanbreda** [comment]
@kitenetter @CCarvell 
Ok yes. I still have a problem with it not syncing with the Warehouse making this more complex than it seems, but I will let you know how I get on.
What about the translations of terms I mentioned? Should the term lists be translated if the rest of the page isn't going to be?

**Comment by kitenetter** [comment]
@andrewvanbreda I'm a bit confused about your final question - can we speak on phone/zoom (see email I sent you for phone number)?

**Comment by kitenetter** [comment]
@CCarvell having spoken to Andy, the issue arises because the terms used for the public FIT Count form are the same set of terms used for the 1 km square FIT Count form. This means that when we add the Welsh terms to the public form, they will also be added to the 1 km form.

Which means that if one of our 1 km square volunteers was to go to the website and choose the Welsh version of it, and then go to the 1 km square FIT Count form, they would see the form in English (because we aren't translating the 1 km forms) but some of the terms used in that form would be in Welsh.

I don't think this needs any action, because we are not expecting any of our 1 km volunteers to be using the Welsh version of the website. Longer-term we may add Welsh translations for the 1 km pages, but for now they are effectively not in use.

**Comment by CCarvell** [comment]
@kitenetter thanks for the explanation - you are right in that this won't be a problem for now, since we don't expect any of our 1 km volunteers to be using the Welsh version.

**Comment by andrewvanbreda** [comment]
@CCarvell @kitenetter 
I fixed the Welsh language problem with the terms this morning. I haven't actually added all the terms yet, but can see it working now.
I also removed those fields from the data entry form. I also removed Identification Experience from the 1km FIT form as it was also there.
I added them to the registration page.
I do have a problem with them and the way they are interacting with the database though, but before explaining what that problem is, could you let me know how you had envisioned retrieving the information about what people had entered for allow contact and Identification experience?.......as currently without going into individual accounts you can't find that information out

**Comment by kitenetter** [comment]
@andrewvanbreda at the moment most analysis for PoMS is done by extracting data from the warehouse via pgAdmin. I hadn't stopped to think about how we would use the data from the new registration process. Am I correct in thinking that the registration data is stored in Drupal but not in the warehouse? If so we will need some way of extracting it, but I don't mind if that is done via the warehouse (if that is possible) or via a Drupal report/view (which would be accessible to admins only).

Is that the issue or is there more to this?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes that is roughly the issue.
The issue being that Indicia is supposed to be able to sync registration fields to warehouse attributes.
This didn't work very well, so I fixed for Drupal 7 NPMS. That works fine now.
But it appears not to work in Drupal 8 at all.
I don't think that can be fixed in time for live. So I can setup a Drupal view with this information on then.

**Comment by kitenetter** [comment]
Drupal view is fine @andrewvanbreda - please can you include a button to download the view as csv.

**Comment by andrewvanbreda** [comment]
@kitenetter Yes, think there is a Drupal module for that.

**Comment by BirenRathod** [comment]
@andrewvanbreda It is called views data export and it is available to enable.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Great thanks Biren

**Comment by kitenetter** [comment]
I think can be closed - will confirm at our catch-up meeting on 28 April.

**Comment by kitenetter** [comment]
Closing.
