### ISSUE TITLE
FIT Count map: display locations as 1km squares

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#61]
Applies to https://test-ceh-poms.pantheonsite.io/node/15

The locations are currently being shown at quite a high resolution for app records - we're aiming to display all counts (including from the app) as blurred to a 1 km square.

**Comment by andrewvanbreda** [comment]
@kitenetter @kazlauskis 
This would probably be because the app is not setting a privacy precision. 
Karolis do you know if the app is setting a privacy_precision of 1000?

Let me know if I can help at all, but I think it is probably at the app end as I think report is working with the other surveys.
Cheers

**Comment by kazlauskis** [comment]
@kitenetter would you like the app to set the precision of 1000?

**Comment by kitenetter** [comment]
@kazlauskis yes, I think we should - we are treating all FIT Count occurrences as 'sensitive' with a blur to 1 km square, on the grounds that many counts will be done in private gardens.

**Comment by kazlauskis** [comment]
Thanks, will do.

**Comment by kitenetter** [comment]
Closing.

**Comment by DavidRoy** [comment]
@kazlauskis I don't think the sample.privacy_precision is being set as required.  If I run this query, all the privacy_precision values are null

select * 
from samples
where survey_id = 641

**Comment by kazlauskis** [comment]
I didn't know you can set the precision to samples, is that what we should do? At the moment, we set it to occurrences (see occurrences from a recent survey from Claire https://warehouse1.indicia.org.uk/index.php/sample/edit/14232193).

**Comment by DavidRoy** [comment]
@andrewvanbreda to advise on what is needed.  Options are:
samples.privacy_precision
occurrences.sensitivity_precision

or both, set to 1000.  I'm not sure if there is a distinction between 'privacy' and 'sensitivity'

**Comment by kitenetter** [comment]
@andrewvanbreda regarding map clicks on iRecord, go to one of the old explore pages:
https://www.brc.ac.uk/irecord/my-records-old
https://www.brc.ac.uk/irecord/all-records-old

If you select the "?" tool from the top-right of the map, and then click on any grid square, the records grid is filtered to show the records that fall under the square you have clicked on. I'm hoping that the PoMS maps can operate in a similar way.

**Comment by andrewvanbreda** [comment]
@kazlauskis @DavidRoy 
Essentially the actual functionality between sensivity_precision and privacy_precision is very much the same apart from one is held against the sample and one against the occurrence. Both blur the map and hide location details.
The main difference is the intention. Privacy precision is mainly used for user privacy reasons. Sensitivity precision is for protecting rare species.
As PoMS is blurring a map of samples because of the need to protect recorder's location privacy we use privacy precision. It is not for species protection reasons.
Indicia should take into account occurrences need to be blurred  from that, although I will test  this to confirm this behaviour.
So for now using sample.privacy_precision and not occurrence.sensitivity_precision.

**Comment by DavidRoy** [comment]
Thanks for the explanation.  In that case the action is for @kazlauskis to apply the value 1000 to samples.privacy_precision

**Comment by kazlauskis** [comment]
Thanks, it's good to know the difference. I will change it to `privacy_precision` then.

**Comment by andrewvanbreda** [comment]
@DavidRoy @kazlauskis 
Just had a look in database just to refresh myself.
Yes this is correct, just set the privacy precision. 
The spatial reference and location information is held at the sample level anyway, so that is where we protect in this case. All occurrences hanging off the sample will be shown at the sample spatial reference.

I did check the bat page I did on iRecord which also has privacy precision of 1000, and that is the behaviour I also observed on the iRecord map.

Worrying about the complex logic of sensitive_precision is not what we need to concern ourselves with here as we are not dealing with sensitive species. I did check with someone (can't remember who) earlier in the project that we are not dealing with sensitive species.

**Comment by kazlauskis** [comment]
@DavidRoy I have changed the app to submit using `privacy_precision` but I cannot test this as the warehouse UI doesn't have this field. I have just uploaded a test sample record `14258170`, could you please check that it contains the desired field in the database?

**Comment by kitenetter** [comment]
@kazlauskis sample with ID = 14258170 has value 1000 in attribute privacy_precision, so it looks like that has worked

**Comment by kazlauskis** [comment]
@kitenetter yay, cheers. Please close it if that's all that was required in the ticket.

**Comment by kitenetter** [comment]
@andrewvanbreda can close if he is happy that this is feeding through correctly to the website maps.

Do we need to do any retrospective updates to the samples previously submitted, and if so can you do that Andy?

**Comment by andrewvanbreda** [comment]
@kitenetter 
Yes these will need updating, I will send you SQL when I get chance, but I am busy with Plant Portal today.

**Comment by kitenetter** [comment]
@andrewvanbreda I don't have update permissions for the warehouse so I'll have to ask you to do that when you get a chance - no immediate hurry.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I have no access at all to the warehouse DB, but I can ask Biren to run it

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Can you run this SQL when you get a chance. Sets all samples in this project to private

update indicia.samples
set privacy_precision=1000
where survey_id in (636,637,638,641) and deleted=false;

insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'sample', id, 100, 2, now()
from indicia.samples
where survey_id in (636,637,638,641) and deleted=false;

**Comment by BirenRathod** [comment]
@andrewvanbreda it has updated 8143 rows.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, without doing exact counting, looking at the other counts we have, this is looks about right.
Just need to wait for the work_queue to finish.

**Comment by CCarvell** [comment]
@andrewvanbreda my apologies I have just created a new issue pointing to this which may overlap - apologies

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren, could you send me this result please so can see if work_queue is finished. Thanks

select count(*) 
from indicia.cache_samples_functional csf
join indicia.cache_samples_nonfunctional csnf on csnf.id = csf.id
where csf.survey_id in (636,637,638,641) and csnf.privacy_precision is null;

**Comment by BirenRathod** [comment]
@andrewvanbreda it returned with 981.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok thanks.
We can have a double-check of this later on. Sounds like it has made good progress. I thought it might of finished actually given the report grid behaviour.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
If you are still in office, I have a nice easy Friday afternoon job for you :) Just a rerun of that statement to make sure it finished. Cheers. Not urgent so can wait.

select count(*)
from indicia.cache_samples_functional csf
join indicia.cache_samples_nonfunctional csnf on csnf.id = csf.id
where csf.survey_id in (636,637,638,641) and csnf.privacy_precision is null;

**Comment by BirenRathod** [comment]
@andrewvanbreda Luckily still working, don't want to leave for next week, so here it is.
Good news, it returned with 0. Have a nice weekend.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren
Thanks is great. :) have nice weekend too.

**Comment by andrewvanbreda** [comment]
Fit Count Map page report code visually inspected for correctness regarding this.
Checked FIT Count Mapping pages (in both languages) setup with correct versions of report.
Checked random selection of squares are blurred on map.
Query sent to Biren showed all samples for our surveys in database are protected.
Visually checked all 3 data entry forms have privacy precision set in configuration (and addditionally Public FIT Count in Welsh).
Added (and removed) some test data entry for 1KM form and found was protected.

I have an issue on may task list where summary popup and grid filtering don't work at same time. I will raise separate issue for that if I can't resolve soon.

Closing.
