### ISSUE TITLE
FIT Count map: zoom control

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/PoMS#62]
Applies to https://test-ceh-poms.pantheonsite.io/node/15

This is a cosmetic issue - the zoom control on the map is currently displaying incorrectly:

![image](https://user-images.githubusercontent.com/16039111/112831805-5c1a9800-908c-11eb-93d5-0c838718f518.png)

Also, the link between dots on the map and records in the grid is not in place (i.e. clicking on one has no effect on the other).

**Comment by andrewvanbreda** [comment]
@kitenetter Ok thanks noted.

**Comment by andrewvanbreda** [comment]
@kitenetter 
I checked this and it is the theme causing this, the other theme is ok when I switched it. It is hard for me to experiment though because I have to commit all the time when I am making site changes.
For now I have changed it to a Pan Zoom control instead of Pan Zoom Bar.
Let me know if you are ok with that style of control, else might need Biren to have a look.

**Comment by BirenRathod** [comment]
@andrewvanbreda I'm happy to have a look if that is causing too much problem. Although the current settings is much better than previous one but that is just my opinion.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
See what Martin says, entirely up to him what he wants. Cheers

**Comment by andrewvanbreda** [comment]
@kitenetter 
Going to close this one, again to reduce the number of open issues. Please re-open if required.
